package com.myspace.customer_greeting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label(value = "Marital Status")
	private java.lang.String maritalStatus;

	public Customer() {
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(java.lang.String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public Customer(java.lang.String gender, java.lang.String maritalStatus) {
		this.gender = gender;
		this.maritalStatus = maritalStatus;
	}

}