package com.myspace.customer_greeting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GreetingRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Current Hour")
	private java.lang.Integer currentHour;

	public GreetingRequest() {
	}

	public java.lang.Integer getCurrentHour() {
		return this.currentHour;
	}

	public void setCurrentHour(java.lang.Integer currentHour) {
		this.currentHour = currentHour;
	}

	public GreetingRequest(java.lang.Integer currentHour) {
		this.currentHour = currentHour;
	}

}